.TH HELLOWORLD 1
.SH NAME
helloworld \- prints "Hello, World! :)\n"
.SH SYNOPSIS
.B helloworld
[\fB\-n\fR \fIBITS\fR]
[\fB\-\-bits\fR \fIBITS\fR]
.IR file ...
.SH DESCRIPTION
.B helloworld
It takes no arguments. All extra details are present to show as sample how to write a \fBman\-page\fR.
.SH OPTIONS
.TP
.BR \-n ", " \-\-bits =\fIBITS\fR
Set the number of bits to modify.
Default is one bit.
