# Generated by Django 2.1.4 on 2019-03-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
