# Generated by Django 2.1.4 on 2019-03-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190325_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
